services:
    nginx:
        build:
            context: ./srcs/requirements/nginx
        ports:
            - "443:443"
        environment:
            - DOMAIN_NAME
        volumes:
            - wordpress:/var/www/html/wordpress/public_html
        networks:
            - internal
        restart: always

    mariadb:
        build:
            context: ./srcs/requirements/mariadb
            args:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - database:/shared/database
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        networks:
            - internal
        restart: always

    wordpress:
        build:
            context: ./requirements/wordpress
            args:
                DOMAIN_NAME: ${DOMAIN_NAME}
        volumes:
            - wordpress:/var/www/html/wordpress/public_html
        environment:
            - DOMAIN_NAME
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
            - WORDPRESS_ADMIN_USER
            - WORDPRESS_ADMIN_PASSWORD
            - WORDPRESS_ADMIN_EMAIL
            - WORDPRESS_USER
            - WORDPRESS_PASSWORD
            - WORDPRESS_EMAIL
        networks:
            - internal
        depends_on:
            - nginx
            - mariadb
        restart: always

volumes:
    wordpress:
        name: wordpress
    database:
        name: mariadb

networks:
    internal:
        driver: bridge
